# Generated by Django 3.2.9 on 2021-12-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211208_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
