# Generated by Django 3.2.9 on 2021-12-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211215_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='haircut_name',
            field=models.CharField(choices=[('Haircut and Shaving 10$', 'Haircut and Shaving 10$'), ('Haircut and Trimming 8$', 'Haircut and Trimming 8$'), ('Haircut 7$', 'Haircut 7$')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Lunch Time', 'Lunch Time'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=50),
        ),
    ]
