# Generated by Django 3.2.9 on 2021-12-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211215_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
