# Generated by Django 3.2.9 on 2021-12-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_roles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(choices=[('Barber', 'Barber'), ('Admin', 'Admin')], max_length=15),
        ),
    ]
