# Generated by Django 3.2.9 on 2021-12-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_roles_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='barber',
            field=models.CharField(choices=[('Antey', 'Antey'), ('Ruslan', 'Ruslan'), ('Alex', 'Alex'), ('Anatoliy', 'Anatoliy')], max_length=20),
        ),
    ]
