# Generated by Django 3.2.9 on 2021-12-18 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_order_barber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
