# Generated by Django 3.2.9 on 2021-12-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211219_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
