# Generated by Django 3.2.9 on 2021-12-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
