# Generated by Django 3.2.9 on 2021-12-18 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(default='teststring', on_delete=django.db.models.deletion.CASCADE, to='main.customers'),
        ),
    ]
