# Generated by Django 3.2.9 on 2021-12-18 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber', models.CharField(choices=[('Antey', 'Antey'), ('Ruslan', 'Ruslan'), ('Alex', 'Alex'), ('Anatoliy', 'Anatoliy')], max_length=20)),
                ('day', models.DateField()),
                ('time', models.CharField(choices=[('Morning', 'Morning'), ('Lunch Time', 'Lunch Time'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=50)),
                ('haircut_name', models.CharField(choices=[('Haircut and Shaving 10$', 'Haircut and Shaving 10$'), ('Haircut and Trimming 8$', 'Haircut and Trimming 8$'), ('Haircut 7$', 'Haircut 7$')], max_length=50)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.customers')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
