# Generated by Django 3.2.9 on 2021-12-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211219_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказss', 'verbose_name_plural': 'Заказыыы'},
        ),
    ]
