# Generated by Django 3.2.9 on 2021-12-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_orders_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
