# Generated by Django 3.2.9 on 2021-12-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='info',
            field=models.TextField(default='Informations'),
        ),
    ]
