# Generated by Django 3.2.9 on 2021-12-18 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_customers_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customers'),
        ),
    ]
